DirectoryPath: _site
CheckDoctype: false
IgnoreURLs:
- "newtheatre.org.uk"
- "alpha.newtheatre.org.uk"
- "history.newtheatre.org.uk"
- "photos.smugmug.com"
- "photos.newtheatre.org.uk"
IgnoreDirs:
- "^lib"

