DirectoryPath: _site
CheckDoctype: false
IgnoreURLs:
- "newtheatre.org.uk"
- "alpha.newtheatre.org.uk"
- "history.newtheatre.org.uk"
- "photos.smugmug.com"
- "photos.newtheatre.org.uk"
- "newtheatre.us3.list-manage.com"
IgnoreDirs:
- "^lib"

