language: ruby
cache:
  bundler: true
  directories:
  - _site/images/resized
  - node_modules/
  - lib/
  - vendor/bundle
  - _smugmug_cache/
  - tmp/
  - ".sass-cache"
install:
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
- npm install
- curl https://s3-eu-west-1.amazonaws.com/wjdp-lib/htmltest > _bin/htmltest
- chmod +x _bin/htmltest
- _bin/htmltest --version
# - bower install
before_script:
- _bin/prep.sh
script:
- bundle exec rake build
- _bin/htmltest
# - bundle exec rake test
after_success:
- _bin/deploy.sh
rvm:
- 2.3.0
env:
  global:
    secure: "RXY9/wcOrr3AjE/tLnvD/nIL8p8XFoP1f08G/k8QWcBlZzJXMqPZGQP+Nx+dETN/H9EPnMUVRlz7Lmrq05LfvSscYHwGXW+2RBUqY65pyb9JHx89Kycs6dAAdexbaswQMdqeWxuD369R1SN2jNTcIKA8lXyOfUg1GDli5KVma+fRlnKu44IU/dWZuZRdlVLCorpPwPxSCIYmG6MpCcNJln3WwxBj6r2JNPP8xMi31WFLVZaxVlkVDE/Jo7cI4W/f8jXJOOXAMzJo998vIdd2euZ/BzgJUHCJM4EnS9hjQs5UxeueVc898DAiE5OlZ6wl+ZBlSTTqLZXkc67ZqeV8ZjrXg2XdcOLPhg17sJLDuGLsnICB763X80kWRbiLLfpKlj8+QVU+Ra+dCEfAPvbk2uwWS6GN+Lu+Gpg0QgNainZY4BnYVR8R71el0Rixpr+m5WejwVEXS+c96OsD0oTX8TkvUwX3PsiwG5nhcXyHLUXyFgRQMjr1P54VXVGb3F7L483PuGvbK+f8I6uk0L7L70VEFopJLUsY10a6359Hs14WBNpIjav9evZnfHR5LFKN/Tkp6lPqPHp8J1ejx+/dNT5yWlyhkUMU6IHNn/IidKZJfuBXwUIEIQnLwbEZbWZuOjLeZmZofplqGgPefTbjZkE5rho4TUapb1N2EWe34cE="
