# Site settings
title: The Nottingham New Theatre
email: boxoffice@newtheatre.org.uk
twitter: thenewtheatre
facebook: thenottinghamnewtheatre 
instagram: nottinghamnewtheatre
uonsu: "https://www.su.nottingham.ac.uk/student-media-groups/newtheatre/"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alpha.newtheatre.org.uk" # the base hostname & protocol for your site
description: "The Nottingham New Theatre is England's only fully student-run theatre producing over 30 productions annually across two venues."
ntbot_endpoint: "https://ntbot.flatcar.xyz/post_issue" # For issue posting

# Build settings
markdown: kramdown
permalink: pretty

plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-coffeescript
- jekyll-jsminify

exclude:
- bower.json
- CNAME.staging
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- Rakefile
- README.md
- robots.txt.staging
- vendor

# sass:
#   style: :compressed

lib:
  js:
    - lib/jquery/dist/jquery.js
    - lib/underscore/underscore.js
    - lib/mousetrap/mousetrap.min.js
    - lib/lunr.js/lunr.min.js

collections:
  content:
    output: true
    permalink: :path/

defaults:
  # Defaults for pages
  - scope:
      type: content
    values:
      layout: default
# Config for the prose editor
prose:
  ignore:
    - .bowerrc
    - .gitignore
    - .travis.yml
    - _bin
    - _coffee
    - _config.yml
    - _includes
    - _layouts
    - _plugins
    - _sass
    - _site
    - bower.json
    - css
    - feeds
    - Gemfile
    - Gemfile.lock
    - js
    - lib
    - package.json
    - robots.txt
  siteurl: "https://alpha.newtheatre.org.uk"
  media: "images"
  # metadata:
