--- 
# Key Dates for the Academic Year

# Auditions and Casting 
## In House 
- alias: ih-proposal-deadline
  name: In House Proposal Deadline
  date: 15th January, 2019
- alias: ih-auditions 
  name: In House Auditions 
  date: 18-19th January, 2019 
- alias: ih-auditions-callbacks 
  name: In House Callbacks 
  date: 20th January, 2019 
- alias: ih-auditions-casting 
  name: In House Casting 
  date: 21st January, 2019 
- alias: ih-season-launch
  name: In House Season Launch 
  date: 27th January, 2019
## Fringe
- alias: fringe-proposal-deadline
  name: Fringe Proposal Deadline 
  date: 15th February, 2019
- alias: fr-auditions 
  name: Fringe Auditions 
  date: 18-19th February, 2019 
- alias: fr-auditions-callbacks 
  name: Fringe Callbacks 
  date: 20th February, 2019 
- alias: fr-auditions-casting 
  name: Fringe Casting 
  date: 21st February, 2019 
- alias: fr-season-launch 
  name: Fringe Season Launch 
  date: 27th February, 2019

# Show Slots 
## In House
- alias: ih-slot-1
  name: In House Slot 1
  date: 1st March, 2019 
- alias: ih-slot-2 
  name: In House Slot 2
  date: 1st March, 2019 
- alias: ih-slot-3
  name: In House Slot 3
  date: 1st March, 2019 
- alias: ih-slot-4
  name: In House Slot 4
  date: 1st March, 2019 
- alias: ih-slot-5
  name: In House Slot 5
  date: 1st March, 2019 
- alias: ih-slot-6
  name: In House Slot 6
  date: 1st March, 2019 
- alias: ih-slot-7
  name: In House Slot 7
  date: 1st March, 2019 

## Fringe
- alias: fr-slot-1
  name: Fringe Slot 1
  date: 1st March, 2019 
- alias: fr-slot-2
  name: Fringe Slot 2
  date: 1st March, 2019 
- alias: fr-slot-3
  name: Fringe Slot 3
  date: 1st March, 2019 
- alias: fr-slot-4
  name: Fringe Slot 4
  date: 1st March, 2019 
- alias: fr-slot-5
  name: Fringe Slot 5
  date: 1st March, 2019 

## Unscripted 
- alias: unscripted-1

## External 
- alias: external-spring
- alias: external-summer

## StuFF 
- alias: stuff 
  name: StuFF
  date: 16-17th June, 2019