---
- alias: ih-proposal-deadline
  name: In House Proposal Deadline
  date: 2nd October, 2019
- alias: ih-auditions
  name: In House Auditions
  date: 10-11th October, 2019
- alias: ih-auditions-callbacks
  name: In House Callbacks
  date: 12th October, 2019
- alias: ih-auditions-casting
  name: In House Casting
  date: 13th October, 2019
- alias: ih-season-launch
  name: In House Season Launch
  date: 9th October, 2019
- alias: fringe-proposal-deadline
  name: Fringe Proposal Deadline
  date: 16th October, 2019
- alias: fr-auditions
  name: Fringe Auditions
  date: 24th-25th October, 2019
- alias: fr-auditions-callbacks
  name: Fringe Callbacks
  date: 26th October, 2019
- alias: fr-auditions-casting
  name: Fringe Casting
  date: 27th October, 2019
- alias: fr-season-launch
  name: Fringe Season Launch
  date: 23rd October, 2019
- alias: ih-slot-1
  name: In House Slot 1
  date: 30th October - 2nd November, 2019
- alias: ih-slot-2
  name: In House Slot 2
  date: 6-9th November, 2019
- alias: ih-slot-3
  name: In House Slot 3
  date: 13th-16th November, 2019
- alias: ih-slot-4
  name: In House Slot 4
  date: 27-30th March, 2019
- alias: ih-slot-5
  name: In House Slot 5
  date: 3rd-6th April, 2019
- alias: ih-slot-6
  name: In House Slot 6
  date: 9-12th April, 2019
- alias: ih-slot-7
  name: In House Slot 7
  date: 15-18th May, 2019
- alias: ih-slot-8
  name: In House Slot 8
  date: 12-15th June, 2019
- alias: fr-slot-1
  name: Fringe Slot 1
  date: 11-12th March, 2019
- alias: fr-slot-2
  name: Fringe Slot 2
  date: 17-19th March, 2019
- alias: fr-slot-3
  name: Fringe Slot 3
  date: 25-26th March, 2019
- alias: fr-slot-4
  name: Fringe Slot 4
  date: 1st-2nd April, 2019
- alias: fr-slot-5
  name: Fringe Slot 5
  date: 7-8th April, 2019
- alias: fr-slot-6
  name: Fringe Slot 6
  date: 13-14th May, 2019
- alias: fr-slot-7
  name: Fringe Slot 7
  date: 9-11th June, 2019
- alias: unscripted-1
- alias: external-spring
- alias: external-summer
- alias: stuff
  name: StuFF
  date: 17th and 18th June, 2019
