---
- alias: ef-casting
  name: EdFringe Casting
  date: ''
- alias: ef-auditions-callbacks
  name: EdFringe Callbacks
  date: ''
- alias: ef-auditions
  name: 'EdFringe Auditions '
  date: ''
- alias: 'ef-proposals-deadline '
  name: EdFringe Proposals Deadline
  date: ''
- alias: ih-proposal-deadline
  name: In House Proposal Deadline
  date: 6th October, 2021
- alias: ih-auditions
  name: In House Auditions
  date: 14th-15th October, 2021
- alias: ih-auditions-callbacks
  name: In House Callbacks
  date: 16th October, 2021
- alias: ih-auditions-casting
  name: In House Casting
  date: 9th February, 2020
- alias: ih-season-launch
  name: In House Season Launch
  date: 13th October, 2021
- alias: fringe-proposal-deadline
  name: Fringe Proposal Deadline
  date: 20th October, 2021
- alias: fr-auditions
  name: Fringe Auditions
  date: 28th-29th October, 2021
- alias: fr-auditions-callbacks
  name: Fringe Callbacks
  date: 30th October, 2021
- alias: fr-auditions-casting
  name: Fringe Casting
  date: 31st October, 2021
- alias: fr-season-launch
  name: Fringe Season Launch
  date: 27th October, 2021
- alias: ih-slot-1
  name: In House Slot 1
  date: 3rd November - 6th November, 2021
- alias: ih-slot-2
  name: In House Slot 2
  date: 4th-7th March, 2020
- alias: ih-slot-3
  name: In House Slot 3
  date: 11th-14th March, 2020
- alias: ih-slot-4
  name: In House Slot 4
  date: 18th-21st March, 2020
- alias: ih-slot-5
  name: In House Slot 5
  date: 25th-28th March, 2020
- alias: ih-slot-6
  name: In House Slot 6
  date: 31st March-3rd April, 2020
- alias: ih-slot-7
  name: In House Slot 7
  date: 6th-9th May, 2020
- alias: ih-slot-8
  name: In House Slot 8
  date: 13th-16th May, 2020
- alias: fr-slot-1
  name: Fringe Slot 1
  date: 8th-10th March, 2020
- alias: fr-slot-2
  name: Fringe Slot 2
  date: 15th-17th March, 2020
- alias: fr-slot-3
  name: Fringe Slot 3
  date: 22nd-24th March, 2020
- alias: fr-slot-4
  name: Fringe Slot 4
  date: 29th-30th March, 2020
- alias: fr-slot-5
  name: Fringe Slot 5
  date: 4th-5th May, 2020
- alias: fr-slot-6
  name: Fringe Slot 6
  date: 10th-12th May, 2020
- alias: fr-slot-7
  name: Fringe Slot 7
  date: ''
- alias: unscripted-1
  name: Unscripted
  date: 11th-14th February, 2020
- alias: external-spring
- alias: external-summer
- alias: stuff
  name: StuFF
  date: 15th and 16th June, 2020 (Provisional date; not yet confirmed)
- alias: audition-deadline
  name: Audition Deadline
  date: 19th February, 2021 at 17:00
- alias: callbacks-2021
  name: Callbacks Announcement for Spring 2021
  date: Friday 19th February
- alias: callbacks-day-2021
  name: Callbacks for Spring 2021
  date: Saturday 20th February
- alias: casting-2021
  name: Casting for Spring 2021
  date: Sunday 21st February
