---
- alias: ih-proposal-deadline
  name: In House Proposal Deadline
  date: 29th January, 2020
- alias: ih-auditions
  name: In House Auditions
  date: 6th-7th February, 2020
- alias: ih-auditions-callbacks
  name: In House Callbacks
  date: 8th February, 2020
- alias: ih-auditions-casting
  name: In House Casting
  date: 9th February, 2020
- alias: ih-season-launch
  name: In House Season Launch
  date: 5th February, 2020
- alias: fringe-proposal-deadline
  name: Fringe Proposal Deadline
  date: 12th February, 2020
- alias: fr-auditions
  name: Fringe Auditions
  date: 20th-21st February, 2020
- alias: fr-auditions-callbacks
  name: Fringe Callbacks
  date: 22nd February, 2020
- alias: fr-auditions-casting
  name: Fringe Casting
  date: 23rd February, 2020
- alias: fr-season-launch
  name: Fringe Season Launch
  date: 19th February, 2020
- alias: ih-slot-1
  name: In House Slot 1
  date: 26th February - 29th February, 2019
- alias: ih-slot-2
  name: In House Slot 2
  date: 4th-7th March, 2020
- alias: ih-slot-3
  name: In House Slot 3
  date: 11th-14th March, 2020
- alias: ih-slot-4
  name: In House Slot 4
  date: 18th-21st March, 2020
- alias: ih-slot-5
  name: In House Slot 5
  date: 25th-28th March, 2020
- alias: ih-slot-6
  name: In House Slot 6
  date: 31st March-3rd April, 2020
- alias: ih-slot-7
  name: In House Slot 7
  date: 6th-9th May, 2020
- alias: ih-slot-8
  name: In House Slot 8
  date: 13th-16th May, 2020
- alias: fr-slot-1
  name: Fringe Slot 1
  date: 8th-10th March, 2020
- alias: fr-slot-2
  name: Fringe Slot 2
  date: 15th-17th March, 2020
- alias: fr-slot-3
  name: Fringe Slot 3
  date: 22nd-24th March, 2020
- alias: fr-slot-4
  name: Fringe Slot 4
  date: 29th-30th March, 2020
- alias: fr-slot-5
  name: Fringe Slot 5
  date: 8th-9th December, 2019
- alias: fr-slot-6
  name: Fringe Slot 6
  date: ''
- alias: fr-slot-7
  name: Fringe Slot 7
  date: ''
- alias: unscripted-1
  name: Unscripted
  date: 11th-14th February, 2020
- alias: external-spring
- alias: external-summer
- alias: stuff
  name: StuFF
  date: 17th and 18th June, 2019
