---
- alias: ef-casting
  name: EdFringe Casting
  date: ''
- alias: ef-auditions-callbacks
  name: EdFringe Callbacks
  date: ''
- alias: ef-auditions
  name: 'EdFringe Auditions '
  date: ''
- alias: 'ef-proposals-deadline '
  name: EdFringe Proposals Deadline
  date: ''
- alias: ih-proposal-deadline
  name: In House Proposal Deadline
  date: 6th October, 2021
- alias: ih-auditions
  name: In House Auditions
  date: 14th-15th October, 2021
- alias: ih-auditions-callbacks
  name: In House Callbacks
  date: 16th October, 2021
- alias: ih-auditions-casting
  name: In House Casting
  date: 9th February, 2020
- alias: ih-season-launch
  name: In House Season Launch
  date: 13th October, 2021
- alias: fringe-proposal-deadline
  name: Fringe Proposal Deadline
  date: 20th October, 2021
- alias: fr-auditions
  name: Fringe Auditions
  date: 28th-29th October, 2021
- alias: fr-auditions-callbacks
  name: Fringe Callbacks
  date: 30th October, 2021
- alias: fr-auditions-casting
  name: Fringe Casting
  date: 31st October, 2021
- alias: fr-season-launch
  name: Fringe Season Launch
  date: 27th October, 2021
- alias: ih-slot-1
  name: In House Slot 1
  date: 3rd November - 6th November, 2021
- alias: ih-slot-2
  name: In House Slot 2
  date: 10th-13th November, 2021
- alias: ih-slot-3
  name: In House Slot 3
  date: 17th-20th November, 2021
- alias: ih-slot-4
  name: In House Slot 4
  date: 24th-27th November, 2021
- alias: ih-slot-5
  name: In House Slot 5
  date: 1st-4th December, 2021
- alias: ih-slot-6
  name: In House Slot 6
  date: 8th-11th December, 2021
- alias: fr-slot-1
  name: Fringe Slot 1
  date: 14th-16th November, 2021
- alias: fr-slot-2
  name: Fringe Slot 2
  date: 21st-23rd November, 2021
- alias: fr-slot-3
  name: Fringe Slot 3
  date: 28th-30th November, 2021
- alias: fr-slot-4
  name: Fringe Slot 4
  date: 5th-7th December, 2021
- alias: fr-slot-5
  name: Fringe Slot 5
  date: 12th-14th November, 2021
- alias: fr-slot-6
  name: Fringe Slot 6
  date: 16th-18th December, 2021
- alias: fr-slot-7
  name: Fringe Slot 7
  date: ''
- alias: unscripted-1
  name: Unscripted
  date: ''
- alias: external-spring
- alias: external-summer
- alias: stuff
  name: StuFF
  date: June, 2022 (Provisional date; not yet confirmed)
- alias: audition-deadline
  name: Audition Deadline
  date: ''
- alias: callbacks-2021
  name: Callbacks Announcement for Spring 2021
  date: ''
- alias: callbacks-day-2021
  name: Callbacks for Spring 2021
  date: ''
- alias: casting-2021
  name: Casting for Spring 2021
  date: ''
