---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: _data/dates.yml
  label: Key Dates
- type: document
  path: _data/committee.yml
  label: Committee
- type: directory
  path: _content
  label: Content
  create: all
  match: "**/*"
- type: document
  path: _data/show-resources.yml
  label: Show Resources
upload_dir: static
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
